services:

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: stratiq-server:latest
    container_name: stratiq-server
    ports:
      - "8000:8000"
    env_file:
      - .env-docker
    environment:
      - PROJECT_ROOT=/app
    restart: unless-stopped

  client:
    build:
      context: ./client/next-js
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - FAST_API_URL=http://server:8000
    image: stratiq-client:latest
    container_name: stratiq-client
    ports:
      - "3000:3000"
    environment:
      - FAST_API_URL=http://server:8000
      - HOSTNAME=0.0.0.0
      - PORT=3000
    depends_on:
      - server
    restart: unless-stopped
